version: '3'

services:

  consul:
    image: sdelrio/consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
      - CONSUL=consul
      - CONSUL_CHECK_LEADER=true
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 45s
        monitor: 15s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s

networks:
  default:
    driver: overlay

    